name: Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: particle_env.yml
          init-shell: bash
      - run: bash test/func/func_testing.sh
        shell: bash -l {0}
  
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: particle_env.yml
          init-shell: bash
      - run: python test/unit/testing_for_github_actions.py
        shell: bash -l {0}
  
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: particle_env.yml
          init-shell: bash
      - run: pycodestyle $(git ls-files "*.py" | grep -v "quickstart_tutorial.py" | grep -v "particle_picker.py")
        shell: bash -l {0}