name: Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: particle_env.yml
          activate-environment: particle
          auto-activate-base: false
          miniforge-version: "24.3.0-0"
          use-mamba: true
      - run: bash test/func/func_testing.sh
        shell: bash -l {0}
  
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: particle_env.yml
          activate-environment: particle
          auto-activate-base: false
          miniforge-version: "24.3.0-0"
          use-mamba: true
      - run: python test/unit/utils_tests.py
        shell: bash -l {0}
  
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: particle_env.yml
          activate-environment: particle
          auto-activate-base: false
          miniforge-version: "24.3.0-0"
          use-mamba: true
      - run: pycodestyle $(git ls-files "*.py" | grep -v "quickstart_tutorial.py" | grep -v "particle_picker.py")
        shell: bash -l {0}